### ISSUE TITLE
不支持 Laravel 5.4

### ISSUE THREAD

**Issue by dntc** [lokielse/laravel-mns#1]
错误信息
FatalErrorException in MNSQueue.php line 11:
Class Lokielse\LaravelMNS\MNSQueue contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Queue\Queue::size)

**Comment by lokielse** [comment]
已更新，请下载最新版本`v1.0.9`

不过目前`size`方法并没有具体实现，因为看了下阿里云的文档，貌似没有提供这个接口。
应该不影响你的使用。

**Comment by dntc** [comment]
已经更新, 生成队列消息没有问题了, 但是使用 php artisan queue:work 消费队列时还是有错误:
Call to undefined method Lokielse\LaravelMNS\Jobs\MNSJob::resolveAndFire()

**Comment by lokielse** [comment]
已更新，请下载最新版本`v1.0.10`,  `fire`方法兼容了新老版本
