### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by WillieOng-HK** [lokielse/laravel-mns#2]
錯誤訊息
local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Lokielse\LaravelMNS\MNSQueue::getSeconds() in /var/www/vhosts/source.com/source.com/vendor/lokielse/laravel-mns/src/MNSQueue.php:102
Stack trace:

**Comment by lokielse** [comment]
fixed in `v1.1.2`
